[build]
  # Specify the build command
  command = "npm run build"

  # Directory where the build output is located
  publish = "out"

[build.environment]
  # Environment variables
  NODE_VERSION = "16"

[[redirects]]
  from = "/api/*"
  to = "/api/index.js"
  status = 200

